# This is a basic workflow to help you get started with Actions

name: Mirror

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - '**'
 
  schedule:
    - cron:  '0 7 * * *'
    # scheduled at 07:00 every Monday and Thursday

  workflow_dispatch:  # click the button on Github repo!  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v1
    - name: mirror-repository
      uses: spyoungtech/mirror-action@v0.4.0
      with:
            REMOTE: ${{ secrets.GIT_REPO }}
            GIT_USERNAME: ${{ secrets.GIT_USER }}
            GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
